# Generated by Django 5.0.6 on 2024-07-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0002_remove_professor_no_empleado_and_more'),
        ('career', '0001_initial'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1, verbose_name='Grupo')),
                ('observations', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('career_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera')),
                ('period_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='period.period', verbose_name='Periodo')),
                ('semester_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='period.semester', verbose_name='Semestre')),
                ('tutor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.student', verbose_name='Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo')),
                ('professor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Profesor')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.subject', verbose_name='Materia')),
            ],
        ),
    ]
