# Generated by Django 5.0.6 on 2024-08-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_professor_no_empleado_and_more'),
        ('career', '0002_alter_career_options_alter_subject_options'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='group_student',
            options={'verbose_name': 'Grupo-Estudiante', 'verbose_name_plural': 'Grupo-Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='group_subject',
            options={'verbose_name': 'Grupo-Materia', 'verbose_name_plural': 'Grupo-Materias'},
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(to='career.subject', verbose_name='Materias'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='academy.student', verbose_name='Estudiantes'),
        ),
    ]
