# Generated by Django 5.0.6 on 2024-06-27 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('TSU', 'Técnico Superior Universitario'), ('ING', 'Ingenieria'), ('MTR', 'Maestria'), ('Lic', 'Licenciatura')], max_length=5)),
                ('short_name', models.CharField(max_length=10)),
                ('status', models.BooleanField(verbose_name=True)),
                ('year_plan', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('total_hours', models.IntegerField()),
                ('weekly_hours', models.IntegerField()),
                ('file', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
