# Generated by Django 5.0.6 on 2024-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
    ]
